from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path
from typing import List, Tuple


REPO_ROOT = Path(__file__).resolve().parents[1]
APP_DIR = REPO_ROOT / "NFTI"
DOCS_DIR = REPO_ROOT / "docs"


@dataclass(frozen=True)
class MenuItem:
    key: str
    label: str


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _extract_menu_items_from_app_py(app_py: Path) -> List[MenuItem]:
    """
    Parse `print(\"N. ...\")` lines inside `show_menu()` as the canonical menu list.
    This makes the docs auto-update when the menu changes.
    """
    src = _read_text(app_py)
    tree = ast.parse(src)

    # Find show_menu() FunctionDef
    show_menu = None
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == "show_menu":
            show_menu = node
            break
    if show_menu is None:
        return []

    items: List[MenuItem] = []
    for node in ast.walk(show_menu):
        # Match: print("1. Pickle the data")
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and node.func.id == "print"
            and node.args
            and isinstance(node.args[0], ast.Constant)
            and isinstance(node.args[0].value, str)
        ):
            s = node.args[0].value.strip()
            if len(s) >= 3 and s[0].isdigit() and s[1] == ".":
                key = s.split(".", 1)[0].strip()
                label = s.split(".", 1)[1].strip()
                items.append(MenuItem(key=key, label=label))

    # De-duplicate while preserving order
    seen = set()
    out: List[MenuItem] = []
    for it in items:
        if it.key not in seen:
            seen.add(it.key)
            out.append(it)
    return out


def _project_tree_overview() -> str:
    """
    Hard-coded overview of the key folders we expect; avoids committing large trees.
    """
    return "\n".join(
        [
            "```text",
            "NFTI/",
            "  app.py                 # CLI menu entrypoint",
            "  test.py                # interactive testing menu for a trained model",
            "  src/                   # core logic",
            "  data/",
            "    schemas/             # header_definitions.csv, customs.csv",
            "    samples/             # small sample CSVs (tracked)",
            "    raw/                 # raw datasets (ignored by git)",
            "  artifacts/             # outputs (ignored by git)",
            "    models/              # keras/xgboost/ensemble model files",
            "    pickles/             # datasets + global pickles",
            "    figures/             # plots",
            "    logs/                # logs",
            "    tuning/              # tuner outputs",
            "    reports/             # missingness and other report files",
            "scripts/",
            "  generate_docs.py        # this generator",
            "docs/",
            "  (generated markdown)",
            "```",
        ]
    )


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def generate_readme(menu: List[MenuItem]) -> str:
    menu_md = "\n".join([f"- **{m.key}**: {m.label}" for m in menu]) if menu else "- (menu not found)"
    return "\n".join(
        [
            "# NFTI",
            "",
            "Schema-driven ML experiments for predicting NFTI (need for trauma interventions) from trauma registry / prehospital-style variables.",
            "",
            "## Quick start",
            "",
            "- **Run the menu app**:",
            "",
            "```bash",
            "cd NFTI",
            "python3 app.py",
            "```",
            "",
            "- **Project data/artifacts layout** is defined in `NFTI/src/paths.py`.",
            "",
            "## Repository layout",
            "",
            _project_tree_overview(),
            "",
            "## Menu options (auto-extracted)",
            "",
            menu_md,
            "",
            "## Notes",
            "",
            "- `NFTI/data/raw/` and `NFTI/artifacts/` are intentionally git-ignored.",
            "- Custom features are defined in `NFTI/data/schemas/customs.csv` and evaluated using a safe arithmetic evaluator.",
            "",
        ]
    )


def generate_docs_structure_md(menu: List[MenuItem]) -> str:
    menu_md = "\n".join([f"- `{m.key}` → {m.label}" for m in menu]) if menu else "- (menu not found)"
    return "\n".join(
        [
            "# Project structure",
            "",
            "This file is auto-generated by `scripts/generate_docs.py`.",
            "",
            "## Key directories",
            "",
            _project_tree_overview(),
            "",
            "## Menu map",
            "",
            menu_md,
            "",
        ]
    )


def main() -> int:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    menu = _extract_menu_items_from_app_py(APP_DIR / "app.py")

    # Root README
    _write(REPO_ROOT / "README.md", generate_readme(menu))

    # docs/*
    _write(DOCS_DIR / "PROJECT_STRUCTURE.md", generate_docs_structure_md(menu))

    print("Wrote README.md and docs/PROJECT_STRUCTURE.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

